name: ON-ISSUE-LABELED
run-name: Issue Labeled ( ${{ github.event.label.name }} )

on:
  issues:
    types: [labeled]

jobs: 

  agile-dev:
    name: Agile Dev
    if: ${{ github.event.label.name == 'status-slfb' }}
    uses: dr3dr3/ss-pipeline/.github/workflows/agile-development.yml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
    secrets: inherit