# Trigger workflows on push to short-lived feature branch (SLFB)
name: Push to SLFB
run-name: Push to SLFB ${{ github.ref_name }}

on:
  push:
    branches-ignore: [main]

jobs: 

  testing:
    name: Test Trigger
    runs-on: ubuntu-latest 
    steps:
      - name: Message
        run: echo "### Test Passed :thumbsup:" >> $GITHUB_STEP_SUMMARY


# if commit message contains "[ci]" then build and test and update PR 