# Trigger workflows on push to short-lived feature branch (SLFB)
name: ON-PUSH-MAIN
run-name: Push to MAIN

on:
  push:
    branches: [main]

jobs:

  # Continuous integration workflow in 'ss-pipeline' repo
  continuous-integration:
    name: CI
    if: ${{  vars.CI_PATTERN == 'TBD_MAIN' }}
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-integration.yml@main
    with: 
      feature: ${{ github.event.head_commit.message }}
      target-ref: ${{ github.sha }}
    permissions:
      contents: write
      pull-requests: write
      pages: write
      id-token: write
    secrets: inherit