# Trigger workflows on pull request review events
name: ON-PR-REQUEST-APPROVAL
run-name: PR approval requested for ${{ github.event.pull_request.head.ref }}

on:
  pull_request:
    types: [labeled]

jobs: 

  # Continuous integration workflow in 'ss-pipeline' repo
  continuous-integration:
    name: CI on SLFB
    if: ${{ github.event.label.name == 'status-pr-to-approve' }}
    uses: dr3dr3/ss-pipeline/.github/workflows/continuous-integration.yml@main
    with: 
      feature: ${{ github.event.pull_request.head.ref }}
      target-ref: ${{ github.sha }}
      solution: 'revealmd'
    permissions:
      contents: write
      issues: write
      pull-requests: write
      pages: write
      id-token: write
    secrets: inherit