# Trigger workflows on push to trunk (main branch)
name: Push to Trunk Events
run-name: Push to Trunk of SLFB ${{ github.ref_name }}

on:
  pull_request:
    types: [closed]

jobs: 

  testing:
    name: Test Trigger
    runs-on: ubuntu-latest 
    steps:
      - name: Message
        run: echo "### Test Passed :thumbsup:" >> $GITHUB_STEP_SUMMARY


# NOTE: PR Merge Workflow uses PAT so this workflow will trigger

# Dispatch to CI
# Purpose: Isolated, mocked/stubbed, automated UI testing?

# Dispatch to STG
# Purpose: Integrated, connected to non-prod, smoke testing?