# Trigger workflows on push to short-lived feature branch (SLFB)
name: ON-PUSH-SLFB
run-name: Push to SLFB ${{ github.ref_name }}

on:
  push:
    branches-ignore: [main]

jobs: 

  # Build static site using Reveal-MD
  build-revealmd:
    name: Build R-MD
    if: ${{ inputs.ss-solution == 'reveal-md' }}
    uses: dr3dr3/ss-pipeline/.github/workflows/build-revealmd.yml@main
    permissions:
      contents: read
    secrets: inherit
    with: 
      target-ref: ${{ github.sha }}
      artefact-ref: ${{ github.sha }}
      deploy-target: 'ci'

  # Deploy CI to GitHub Pages
  # Only run if commit message contain "[ci]"
  deploy-ci:
    name: Deploy CI
    needs: [build-revealmd]
    if: ${{ contains(github.event.head_commit.message, '[ci]') }}    
    uses: dr3dr3/ss-pipeline/.github/workflows/deploy-github-pages.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
    secrets: inherit
    with:
      target-ref: ${{ github.sha }}
      artefact-ref: ${{ github.sha }}
      deploy-target: 'ci'
