# Trigger workflows on push to short-lived feature branch (SLFB)
name: ON-PUSH-SLFB
run-name: Push to SLFB ${{ github.ref_name }}

on:
  push:
    branches-ignore: [main]

jobs: 

  # Deploy CI to GitHub Pages
  # Only run if commit message contain "[ci]"
  deploy-ci:
    name: Deploy CI
    if: ${{ contains(github.event.head_commit.message, '[ci]') }}    
    uses: dr3dr3/ss-pipeline/.github/workflows/deploy-github-pages.yml
    with:
      target-ref: ${{ github.sha }}
      artefact-ref: ${{ github.sha }}
      deploy-target: 'ci'